name: build

on:
  push:
    branches: null
  pull_request:
    branches: null

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { os: ubuntu-latest, ghc: ghc884 }
          - { os: ubuntu-latest, ghc: ghc8107 }
          # - { os: macos-latest, ghc: ghc8107 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with: { nix_path: 'nixpkgs=channel:nixos-21.05' }

      - uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - if: ${{ matrix.os != 'macos-latest' }}
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt &

      - run: nix-shell --run 'bazel build //... --host_platform=//tools/platforms:${{ matrix.ghc }}'
