name: build

on:
  push:
    branches: null
    paths-ignore:
      - 'scripts/**'
      - 'config/**'
      - 'cabal.project'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: null

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, ghc: 884  }
          - { os: ubuntu-latest, ghc: 8107 }
          - { os: macos-latest,  ghc: 8107 }

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |-
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt &

      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=./nix/nixpkgs.nix

      - name: Restore repository cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel/amazonka/repo
          key: repo-cache-${{ runner.os }}

      - name: Configure
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: |
          cat >.bazelrc.local <<EOF
          common --config=ci
          build --remote_header=x-buildbuddy-api-key="$BUILDBUDDY_API_KEY"
          EOF

      - name: Build and test
        run: |
          nix-shell --argstr ghcVersion '${{ matrix.ghc }}' --run '
            set -euo pipefail
            bazel build //... --build_tag_filters=ci
            bazel test  //... --build_tag_filters=ci
            '

      # FIXME: add additional check for docs deploy github.ref == 'refs/heads/main'
      # - name: Build and test
      #   run: |
      #     nix-shell --argstr ghcVersion '${{ matrix.ghc }}' --run '
      #       bazel build //docs
      #       '

      - if: ${{ github.repository == 'brendanhay/amazonka' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: bazel-bin/docs/docs
