name: build

on:
  push:
    branches: null
    paths-ignore:
      - '**.md'
      - 'scripts'
  pull_request:
    branches: null

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, ghc: 884  }
          - { os: ubuntu-latest, ghc: 8107 }
          - { os: macos-latest,  ghc: 8107 }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=./nix/nixpkgs.nix

      - name: Setup nix cache
        uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Setup local bazel cache
        uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}-${{ matrix.ghc }}
          restore-keys: |
            cache-${{ runner.os }}
          path: |
            ~/.cache/bazel/amazonka

      - name: Setup writable remote bazel cache
        if: ${{ github.repository == 'brendanhay/amazonka' }}
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          cp .bazelrc.{ci,local}

          printf '%s\n' >/tmp/credentials.json \
            "$SERVICE_ACCOUNT"

      - name: bazel build //...
        run: |
          nix-shell --argstr ghcVersion '${{ matrix.ghc }}' --run \
            'bazel build //... --build_tag_filters=ci'

      - name: bazel build //gen
        if: ${{ matrix.ghc == '8107' }}
        run: |
          nix-shell --argstr ghcVersion '${{ matrix.ghc }}' --run \
            'bazel build //gen'

      - name: bazel test //...
        if: ${{ matrix.ghc == '8107' }}
        run: |
          nix-shell --argstr ghcVersion '${{ matrix.ghc }}' --run \
            'bazeltest build //... --build_tag_filters=ci'
