name: build

env:
  # Bump this number to invalidate the github actions cache.
  cache-version: 0

on:
  push:
    branches: null
  pull_request:
    branches: null

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
#          - { os: ubuntu-latest, ghc: ghc884  }
          - { os: ubuntu-latest, ghc: ghc8107 }
#          - { os: macos-latest,  ghc: ghc8107 }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: 'nixpkgs=./nix/nixpkgs.nix'

      - name: Setup nix cache
        uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Setup local bazel cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: cache-${{ runner.os }}-${{ env.cache-version }}

      - name: Setup writable remote bazel cache
        if: ${{ github.repository == 'brendanhay/amazonka' }}
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          printf '%s\n' >/tmp/credentials.json \
            "$SERVICE_ACCOUNT"

          printf '%s\n' >>.bazelrc.local \
            "build  --google_credentials=/tmp/credentials.json" \
            "build  --remote_upload_local_results=true"

      - name: bazel build //amazonka
        run: |
          # Avoid using shell.nix because we only need bazel, not all buildInputs.
          nix-shell -p bazel --run \
            'bazel build //... --host_platform=//tools/platforms:${{ matrix.ghc }}'
