name: docs

on:
  push:
    branches: null

jobs:
  docs:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=./nix/nixpkgs.nix

      - name: Setup nix cache
        uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Setup local bazel cache
        uses: actions/cache@v2
        with:
          key: cache-${{ runner.os }}
          path: |
            ~/.cache/bazel

      - name: Setup writable remote bazel cache
        if: ${{ github.repository == 'brendanhay/amazonka' }}
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          printf '%s\n' >/tmp/credentials.json \
            "$SERVICE_ACCOUNT"

          printf '%s\n' >>.bazelrc.local \
            "common --google_credentials=/tmp/credentials.json" \
            "common --remote_upload_local_results=true" \
            "common --curses=no" \
            "common --color=no"

      - name: bazel build //docs
        run: nix-shell --run 'bazel build //docs'

      - name: Push to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: bazel-bin/docs/docs
