name: gen

on:
  workflow_dispatch: null
  schedule:
    - cron: '0 0 * * *'

jobs:
  gen:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, ghc: 8107  }

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |-
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt &

      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=./nix/nixpkgs.nix

      - name: Restore repository cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel/amazonka/repo
          key: repo-cache-${{ matrix.os }}-${{ matrix.ghc }}

      - name: Configure
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: |
          cat >.bazelrc.local <<EOF
          common --config=ci
          build --remote_header=x-buildbuddy-api-key="$BUILDBUDDY_API_KEY"
          EOF

      - name: Build and test
        run: |
          nix-shell --argstr ghcVersion '${{ matrix.ghc }}' --run '
            ./scripts/generate-configs
            ./scripts/generate
            '
